#!/bin/bash
yum -y install nagios
systemctl enable nagios
systemctl start nagios
setenforce 0
yum -y install httpd
systemctl enable httpd
systemctl start httpd
yum -y install nrpe
systemctl enable nrpe
systemctl start nrpe
yum -y  install nagios-plugins-all
yum -y install nagios-plugins-nrpe
htpasswd -c /etc/nagios/passwd nagiosadmin
chmod 666 /var/log/nagios/nagios.log 
mkdir /etc/nagios/servers
sed -i '51 s/^#//' /etc/naios/nagios.cfg 

/usr/sbin/nagios -v /etc/nagios/nagios.cfg
systemctl restart nagios

#we also used this for the server
./generate_config.sh web-a2 10.150.0.2
systemctl restart nagios
echo "define command{
                                command_name check_nrpe
                                command_line /usr/lib64/nagios/plugins/check_nrpe -H $HOSTADDRESS$ -c $ARG1$
                                }" >> /etc/nagios/objects/commands.cfg

#for the client
#yum -y install nagios-nrpe-server nagios-plugins
#yum -y install nrpe
#sed -i 's/allowed_hosts=127.0.0.1/allowed_hosts=127.0.0.1, 10.150.0.2/g' /etc/nagios/nrpe.cfg
#systemctl restart nrpe

