#!/bin/bash
#tried this first
yum install -y rpm-build

#tried this second - neither gave me the directories i thought they would
yum -y install yum-utils rpmbuild

#ran from Ms. Bade and then i had the directories i thought i would
yumdownloader --source nrpe
yumdownloader --source nagios

#ran this tosee where the top dir was
rpm --showrc | grep topdir

#to run the code?? - i went and looked in: cd /root/rpmbuild/SOURCES/ and the tar files were there for each
rpm -ivh ./nrpe-3.2.1-8.el7.src.rpm
rpm -ivh ./nagios-4.4.3-1.el7.src.rpm

#cd'd into /usr/local/src dir to run the tar.gz source code from root

#ran the following out of /usr/local/src from root
tar xvzf /root/rpmbuild/SOURCES/nrpe-3.2.1.tar.gz
tar xvzf /root/rpmbuild/SOURCES/nagioscore-nagios-4.4.3.tar.gz

#found spec files in /root/rpmbuild/SPECS for nagios.spec and nrpe.spec
#cp ea to /usr/local/src with the intent of pushing up
yum -y install git
git clone https://github.com/dakoda17/NTI-320.git NTI-320

#add the files of the specs to the NTI-320 directory, then from the directory
#git add <file>
#git commit -m "adding file"
#git push and refresh the git pageGRP 

#cd's into # cd /root/rpmbuild/SPECS
# rpmbuild -ba nagios.spec
# rpmbuild -ba nrpe.spec

#from specs solder ran for nagios:
yum install libxstl-devel #nothing to do
yum -y install libvorbis-devel
yum -y install doxygen
yum -y install gcc
yum -y install gd-devel gperf libjpeg-devel
yum -y install perl-generators
#this was said no package nothing to do
#yum -y install perl CPAN
yum -y install libtool
yum -y install selinux-policy-devel

#from specs solder ran for nrpes:
yum -y install openssl-devel tcp_wrappers-devel
#then ran and the file took a long time to execute:
rpmbuild -ba nrpe.spec








